### ISSUE TITLE
Doesn't start since usbutils added

### ISSUE THREAD

**Issue by cybersphinx** [flathub/cc.arduino.arduinoide#19]
The current version has "command=usbhid-dump" in its metadata file, which aborts with a confusing error about usb permissions, and some previous versions run bin/usb-devices instead. Looks like it just puts a random binary there when nothing is specified, adding the right command to cc.arduino.arduinoide.json will probably fix it.

**Comment by A6GibKm** [comment]
Could you be more specific? Mine works fine. The commit added `lsusb	lsusb.py  usb-devices  usbhid-dump` to `/app/bin` would this issue be fixed if we remove `usb-devices` and `usbhid-dump`?

**Comment by cybersphinx** [comment]
flatpak/app/cc.arduino.arduinoide/x86_64/stable/5397f5d322a10e466ccdce29d97ed2d7aaaa859ca4eb9b80d4fab83f22101d46/metadata

contains 

```
[Application]
name=cc.arduino.arduinoide
runtime=org.freedesktop.Platform/x86_64/19.08
sdk=org.freedesktop.Sdk/x86_64/19.08
command=usbhid-dump
```

so when running flatpak/exports/bin/cc.arduino.arduinoide it runs .../bin/usbhid-dump instead of .../bin/arduino. Looking at e.g. 
https://github.com/flathub/org.kde.kdenlive/blob/master/org.kde.kdenlive.json#L7 which also has several binaries in its bin directory adding

```"command": "arduino",```

to cc.arduino.arduinoide.json should make sure that it always calls the correct binary.

Just removing usbhid-dump won't help, because e.g. in version 4765aff8fdeb33c0c7538483f253227f1b1f4e665fb29e4565920afab067f8e6 metadata contains `command=usb-devices` instead.

**Comment by A6GibKm** [comment]
Today I learned that "command" was optional. I will push the PR, it will take a few hours to be live.
