### ISSUE TITLE
Wrong Python version - problem with esptool

### ISSUE THREAD

**Issue by speendo** [flathub/cc.arduino.arduinoide#23]
Thanks for this flatpak.
I installed it on my Debian Testing machine but cannot compile sketches for ESP32 boards. This is what I get:

> Traceback (most recent call last):
>   File "/home/marcel/.arduino15/packages/esp32/tools/esptool_py/2.6.1/esptool.py", line 37, in <module>
>     import serial
> ModuleNotFoundError: No module named 'serial'
> exit status 1

As far as I could dig into this issue, I think it is caused by the dependency on the [flathub shared libraries](https://github.com/flathub/shared-modules). The shared modules seem to provide only Python 2.7.18.

As Python 2 is dying, Debian Testing does not provide `/usr/bin/python` at the moment. A sustainable solution would probably be a switch to Python 3 which is however not provided by flathub shared modules.

I hope a maintainer can soon find a solution.

**Comment by A6GibKm** [comment]
The flatpak uses python3, python2 is not even bundled (but could if needed). I will add the serial python3 module later today.

Note that the only shared-module that it is installed is libusb.

**Comment by speendo** [comment]
I see. Thanks for your help and sorry for not looking closer.at this

**Comment by A6GibKm** [comment]
> I see. Thanks for your help and sorry for not looking closer at this

Don't worry, thanks for reporting.

@speendo could you please try #24 once it finishes compiling (it has not started yet for some reason)? I will trigger a rebuild later.

**Comment by speendo** [comment]
Thank you Maximiliano!

Now I get

> Traceback (most recent call last):
>   File "/home/marcel/.arduino15/packages/esp32/tools/esptool_py/2.6.1/esptool.py", line 45, in <module>
>     raise ImportError("""
> ImportError: 
> esptool.py depends on pyserial, but there is a conflict with a currently installed package named 'serial'.
> 
> You may be able to work around this by 'pip uninstall serial; pip install pyserial' but this may break other installed Python software that depends on 'serial'.
> 
> There is no good fix for this right now, apart from configuring virtualenvs. See https://github.com/espressif/esptool/issues/269#issuecomment-385298196 for discussion of the underlying issue(s).
> exit status 1

Is it possible that you should `pyserial` instead of `serial`?

**Comment by A6GibKm** [comment]
Oops, done, this time the bot started building automatically.

**Comment by speendo** [comment]
yes! It works for me now. Thank you!

**Comment by FilipDominec** [comment]
My observation is that 
1. esptool.py works on Ubuntu Bionic
2. esptool.py fails on Ubuntu Focal, where pyserial is no longer available for Python2
3. one can run ```python3 esptool.py``` on Ubuntu Focal (when pyserial is installed for Python3); maybe this is the solution to the upload troubles
