### ISSUE TITLE
Cannot use digispark integration due to missing libusb-0.1

### ISSUE THREAD

**Issue by phako** [flathub/cc.arduino.arduinoide#26]
The existing digispark/digistump board integration uses a prebuilt micronucleus that requires libusb-0.1:
`
/home/jgeorg/.arduino15/packages/digistump/tools/micronucleus/2.0a4/micronucleus: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory`
(Updated integration Installed from https://github.com/ArminJo/DigistumpArduino, I believe the old digistump package even uses a 32bit pre-compiled executable)

**Comment by A6GibKm** [comment]
We are already shipping libusb-1 I think (I am not sure how they are versioned, just that we use the latest).

**Comment by phako** [comment]
Yes, but that needs the compatibility wrapper for the old libusb api  (libusb vs libusb-1)

**Comment by naikymen** [comment]
Hi, same here!

Apparently both versions, 1 and 0.1, are needed: http://digistump.com/wiki/digispark/tutorials/linuxtroubleshooting#libusb

**Comment by hadess** [comment]
the libusb-0.1 module code is available at https://github.com/flathub/org.gnome.OCRFeeder/blob/master/sane-backends.yaml#L24-L47

Looks like a good first contribution.

If you actually need a 32-bit libusb, it gets more complicated, but I've recently done that in Kega Fusion:
https://github.com/flathub/com.carpeludum.KegaFusion/blob/master/com.carpeludum.KegaFusion.yml

Feel free to ping me if once you've made the changes to build libusb-0.1 and you're stuck trying to make it build a 32-bit version.

**Comment by A6GibKm** [comment]
Patches are welcome, if you do an PR and confirm that it works I'll happily merge it.

**Comment by juceliodelmondes** [comment]
Same problem on Deepin Linux

**Comment by rtek1000** [comment]
Hello, I had this error in Xubuntu 22.04 [Ubuntu 22.04.1 LTS (Jammy Jellyfish)]:

> micronucleus: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory

This error was resolved using this command:

> sudo apt-get install libusb-0.1-4

Note:

I used this tutorial to get started, it's pretty complete:

https://startingelectronics.org/tutorials/arduino/digispark/digispark-linux-setup/

**Comment by hadess** [comment]
> Hello, I had this error in Xubuntu 22.04 [Ubuntu 22.04.1 LTS (Jammy Jellyfish)]:
> 
> > micronucleus: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory
> 
> This error was resolved using this command:
> 
> > sudo apt-get install libusb-0.1-4

Those steps aren't relevant to running `micronucleus` inside Flatpak, which is what this issue was about. The shared library in question is already in the ArduinoCC Flatpak.

**Comment by ME-MANUPULATOR** [comment]
/home/green/.arduino15/packages/digistump/tools/micronucleus/2.0a4/micronucleus: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory


This is what it shows when i try to program something on arduino ide for my digispart ATtiny 85. please help me out to solve this problem.

**Comment by A6GibKm** [comment]
> /home/green/.arduino15/packages/digistump/tools/micronucleus/2.0a4/micronucleus: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory
> 
> 
> This is what it shows when i try to program something on arduino ide for my digispart ATtiny 85. please help me out to solve this problem.

From your output I think this is not related to the flatpak for arduino

**Comment by ME-MANUPULATOR** [comment]
flatpack for arduino? i seriously dont have idea abt what u are talking. i bought this digispark ATtiny85 . poeple said i can input command to test on other pc devices. and now i shifted from windows to pc so i set up all the ardiuno ide from first but when i put the code and complete it shows the error . can u tell me how to fix it or prescribe me any link to solve this error please

**Comment by A6GibKm** [comment]
This is the repository for the flatpak distribution of the arduino ide, please go to their user forums for help if using another distribution method for the app.
