### ISSUE TITLE
Update to Arduino IDE 2.0

### ISSUE THREAD

**Issue by A6GibKm** [flathub/cc.arduino.arduinoide#29]
Following https://blog.arduino.cc/2021/03/01/announcing-the-arduino-ide-2-0-beta/ it would be a good idea to have a working build of this beta on the `beta` branch to be ready for its launch.

**Comment by joshuag1000** [comment]
This issue needs closing.

**Comment by A6GibKm** [comment]
Yes, now there is a separate flatpak for it at https://github.com/flathub/cc.arduino.IDE2.
