### ISSUE TITLE
SSL SunCertPathBuilderException

### ISSUE THREAD

**Issue by MaSven** [flathub/cc.arduino.arduinoide#3]
I also opened this issue here [7948](https://github.com/arduino/Arduino/issues/7948).
It seems like this is build with openjdk10 and arduinoIDE is not supporting java9+. Dont know if this is the problem or its just the jre used by this flatpak.

**Comment by nedrichards** [comment]
Thanks for opening upstream, yeah. Looks like this needs openjdk-8. There isn't an *easy* flatpak SDK extension for that at the moment but obviously it'll have to be done by someone.

**Comment by MaSven** [comment]
I tried to bunlde openjdk8 with the arduino ide. But i dont know how to bundle the gtk2 lib with it since java8 depends on it. Also the ArduinoIDE needs this because it is setting the swing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel. You can have a look here for it [fork](https://github.com/MaSven/cc.arduino.arduinoide/commit/3a892e7d32425db5cf2209a733f1779af8ba0f39).

**Comment by mbooth101** [comment]
Hi, would it be possible to try building with the latest openjdk11 extension?

I have fixed some SSL problems recently, and would love if this started working :-)

**Comment by A6GibKm** [comment]
This is being build with openjddk11 since #10
