### ISSUE TITLE
Doesn't register to open *.ino files

### ISSUE THREAD

**Issue by bastianilso** [flathub/cc.arduino.arduinoide#7]
I have Arduino IDE installed, but Arduino IDE doesn't register itself to open the *.ino files on my computer and I cannot find it in the list of applications either. This forces me to open the IDE and use "File -> Open.." instead of being able to open directly the *.ino files from Nautilus.

**Comment by muelli** [comment]
FWIW: The needed file is probably /app/share/mime/packages/$appid.xml
