### ISSUE TITLE
Save As.. yields errors and saves the *.ino files into a folder with the same name

### ISSUE THREAD

**Issue by bastianilso** [flathub/cc.arduino.arduinoide#8]
When I use File->Save As.. from the Flatpak Arduino IDE and give the file a name (fx "test123"), the IDE creates a folder inside the specified file path named "test123" and also creates an *.ino file named (test123.ino) within that folder.

If I use File->Save As.. and try to replace an existing file, Arduino IDE, deletes the old file, creates a folder called "myfile.ino" and then creates a file inside called "myfile.ino.ino".

**Comment by bastianilso** [comment]
In some cases Save As.. yields an error dialog preventing the saving operation completes and instead warns that the operation I was about to do would go on forever and ever.

**Comment by A6GibKm** [comment]
I was not able to reproduce, since this is an old issue I am closing this for now. Feel free to reopen it if it persists.
